### ISSUE TITLE
https/http configuration issue with thredds godiva

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#982]
I'm not sure if this is thredds issue or not, but I'm having an issue with thredds generating the godiva2 links with http instead of https. 

 I just installed the latest stable TDS Docker container and nginx is handling requests through port 80 and providing https for the container. 

The datasets are secure and look fine:
https://js-170-55.jetstream-cloud.org/thredds/catalog/data/Sandy/catalog.html?dataset=data/Sandy/Sandy_ocean_his.nc

but if you click on "godiva2" viewer at the bottom, this URL is generated:
https://js-170-55.jetstream-cloud.org/thredds/godiva2/godiva2.html?server=http://js-170-55.jetstream-cloud.org/thredds/wms/data/Sandy/Sandy_ocean_his.nc

That doesn't work because it *should* be 
https://js-170-55.jetstream-cloud.org/thredds/godiva2/godiva2.html?server=https://js-170-55.jetstream-cloud.org/thredds/wms/data/Sandy/Sandy_ocean_his.nc
(which does work).

How can I get thredds to put that https in the godiva2 links?

**Comment by lesserwhirls** [comment]
All of the top level URLs used in the TDS are using whatever the servlet container "sees" as the top level URL, including the protocol. The servlet container (we use tomcat) looks at the incoming requests to figure out what the top level URL is. In this case, nginx is making the call to the servlet container, and some of the time it the container gets the right info, sometimes not.

What does your nginx config look like? It would be useful to test this setup locally. Note, I have *zero* experience with nginx, so it might take some time to sort out.

**Comment by rsignell-usgs** [comment]
@oxelson , any insight here?

My nginx conf looks like:
```
server {
       listen         80;
       server_name    js-170-55.jetstream-cloud.org;
       return         301 https://$host$request_uri;
}


server {
  listen      443 ssl;

  server_name js-170-55.jetstream-cloud.org;


# thredds

  location /thredds/ {
    proxy_set_header Host $host;
    proxy_read_timeout 3600;
    proxy_pass http://js-170-55.jetstream-cloud.org:8080/thredds/;
    include /etc/nginx/conf.d/include/cors.include;
  }
```

**Comment by rsignell-usgs** [comment]
For reference, my `docker-compose.yml` running `nginx` and `tds` looks like this:
```
nginx:
  image: bradjonesllc/docker-nginx-letsencrypt
  ports:
    - "80:80"
    - "443:443"
  container_name: nginx
  volumes:
    - /opt/docker/brad/dhparam:/etc/ssl/dhparam
    - /opt/docker/brad/letsencrypt:/etc/letsencrypt
    - /opt/docker/nginx/html:/etc/nginx/html
    - /opt/docker/nginx/conf.d/brad.conf:/etc/nginx/conf.d/brad.conf
    - /opt/docker/nginx/conf.d/include/cors.include:/etc/nginx/conf.d/include/co
rs.include
  environment:
    - "CERTS=js-170-55.jetstream-cloud.org"
    - "EMAIL=rsignell@usgs.gov"

###
# tds:  THREDDS Data Server- Development
###
tds:
  image: unidata/thredds-docker:4.6.12-SNAPSHOT
  ports:
    - "8080:8080"
  container_name: tds
  volumes:
    - /opt/docker/tds/tomcat/logs/:/usr/local/tomcat/logs/
    - /opt/docker/tds/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
    - /opt/docker/tds/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat
-users.xml
    - /opt/docker/tds/thredds/:/usr/local/tomcat/content/thredds
    - /data:/data:ro
```
